version: '3'

services:
    localRabbitMQ:
      image: rabbitmq:3-management-alpine
      environment:
        RABBITMQ_DEFAULT_USER: root
        RABBITMQ_DEFAULT_PASS: root

      ports:
        - 5672:5672
        - 15672:15672